export const STOCK_LIST = [
  { name: "Apple", exchange: "NASDAQ", ticker: "AAPL" },
  { name: "Microsoft", exchange: "NASDAQ", ticker: "MSFT" },
  { name: "Alphabet", exchange: "NASDAQ", ticker: "GOOG" },
  { name: "Amazon", exchange: "NASDAQ", ticker: "AMZN" },
  { name: "Nvidia", exchange: "NASDAQ", ticker: "NVDA" },
  { name: "Meta", exchange: "NASDAQ", ticker: "META" },
  { name: "Tesla", exchange: "NASDAQ", ticker: "TSLA" },
  { name: "Broadcom", exchange: "NASDAQ", ticker: "AVGO" },
  { name: "ASML", exchange: "NASDAQ", ticker: "ASML" },
  { name: "Starbucks Corporation", exchange: "NASDAQ", ticker: "SBUX" },
  { name: "Gilead Sciences, Inc.", exchange: "NASDAQ", ticker: "GILD" },
  {
    name: "Regeneron Pharmaceuticals, Inc.",
    exchange: "NASDAQ",
    ticker: "REGN",
  },
  { name: "Accenture", exchange: "NYSE", ticker: "ACN" },
  { name: "Thermo Fisher Scientific", exchange: "NYSE", ticker: "TMO" },
  { name: "SAP", exchange: "NYSE", ticker: "SAP" },
  { name: "Pepsico", exchange: "NYSE", ticker: "PEP" },
  { name: "Linde", exchange: "NYSE", ticker: "LIN" },
  { name: "Abbott Laboratories", exchange: "NYSE", ticker: "ABT" },
  { name: "Shell", exchange: "NYSE", ticker: "SHEL" },
  { name: "AstraZeneca", exchange: "NYSE", ticker: "AZN" },
  { name: "Novartis", exchange: "NYSE", ticker: "NVS" },
  { name: "Wells Fargo", exchange: "NYSE", ticker: "WFC" },
  { name: "Walt Disney", exchange: "NYSE", ticker: "DIS" },
  { name: "Cisco", exchange: "NYSE", ticker: "CSCO" },
  { name: "T-Mobile US", exchange: "NYSE", ticker: "TMUS" },
  { name: "QUALCOMM", exchange: "NASDAQ", ticker: "QCOM" },
  { name: "Danaher", exchange: "NYSE", ticker: "DHR" },
  { name: "Intel", exchange: "NASDAQ", ticker: "INTC" },
  { name: "Alibaba", exchange: "NYSE", ticker: "BABA" },
  { name: "General Electric", exchange: "NYSE", ticker: "GE" },
  { name: "Intuit", exchange: "NASDAQ", ticker: "INTU" },
  { name: "IBM", exchange: "NYSE", ticker: "IBM" },
  { name: "Tata Consultancy Services", exchange: "NYSE", ticker: "TCS.NS" },
  { name: "Applied Materials", exchange: "NASDAQ", ticker: "AMAT" },
  { name: "Caterpillar", exchange: "NYSE", ticker: "CAT" },
  { name: "Comcast", exchange: "NASDAQ", ticker: "CMCSA" },
  { name: "Bank of China", exchange: "NYSE", ticker: "601988.SS" },
  { name: "Verizon", exchange: "NYSE", ticker: "VZ" },
  { name: "Uber", exchange: "NYSE", ticker: "UBER" },
  { name: "American Express", exchange: "NYSE", ticker: "AXP" },
  { name: "China Construction Bank", exchange: "NYSE", ticker: "601939.SS" },
  { name: "Dior", exchange: "NYSE", ticker: "CDI.PA" },
  { name: "Siemens", exchange: "NYSE", ticker: "SIE.DE" },
  { name: "Texas Instruments", exchange: "NASDAQ", ticker: "TXN" },
  { name: "ServiceNow", exchange: "NYSE", ticker: "NOW" },
  { name: "Pfizer", exchange: "NYSE", ticker: "PFE" },
  { name: "TotalEnergies", exchange: "NYSE", ticker: "TTE" },
  { name: "Union Pacific Corporation", exchange: "NYSE", ticker: "UNP" },
  { name: "Nike", exchange: "NYSE", ticker: "NKE" },
  { name: "Amgen", exchange: "NYSE", ticker: "AMGN" },
  { name: "Pinduoduo", exchange: "NASDAQ", ticker: "PDD" },
  { name: "BHP Group", exchange: "NYSE", ticker: "BHP" },
  { name: "Philip Morris", exchange: "NYSE", ticker: "PM" },
  { name: "HSBC", exchange: "NYSE", ticker: "HSBC" },
  { name: "Mondelez International, Inc.", exchange: "NASDAQ", ticker: "MDLZ" },
  { name: "Lam Research Corporation", exchange: "NASDAQ", ticker: "LRCX" },
  {
    name: "Automatic Data Processing, Inc.",
    exchange: "NASDAQ",
    ticker: "ADP",
  },
  { name: "Analog Devices, Inc.", exchange: "NASDAQ", ticker: "ADI" },
  { name: "Micron Technology, Inc.", exchange: "NASDAQ", ticker: "MU" },
  { name: "Airbnb, Inc.", exchange: "NASDAQ", ticker: "ABNB" },
  { name: "MercadoLibre, Inc.", exchange: "NASDAQ", ticker: "MELI" },
  { name: "KLA Corporation", exchange: "NASDAQ", ticker: "KLAC" },
  { name: "Equinix, Inc. (REIT)", exchange: "NASDAQ", ticker: "EQIX" },
  { name: "Synopsys, Inc.", exchange: "NASDAQ", ticker: "SNPS" },
  { name: "CME Group Inc.", exchange: "NASDAQ", ticker: "CME" },
  { name: "Workday, Inc.", exchange: "NASDAQ", ticker: "WDAY" },
  { name: "Cadence Design Systems, Inc.", exchange: "NASDAQ", ticker: "CDNS" },
  { name: "CSX Corporation", exchange: "NASDAQ", ticker: "CSX" },
  { name: "Conversion Labs, Inc.", exchange: "NASDAQ", ticker: "CVLB" },
  { name: "Adobe Systems", exchange: "NASDAQ", ticker: "ADBE" },
  { name: "Salesforce", exchange: "NYSE", ticker: "CRM" },
  { name: "PayPal Holdings", exchange: "NASDAQ", ticker: "PYPL" },
  { name: "Oracle Corporation", exchange: "NYSE", ticker: "ORCL" },
  { name: "Honeywell International", exchange: "NASDAQ", ticker: "HON" },
  { name: "Goldman Sachs Group", exchange: "NYSE", ticker: "GS" },
  { name: "Morgan Stanley", exchange: "NYSE", ticker: "MS" },
  { name: "Netflix", exchange: "NASDAQ", ticker: "NFLX" },
  { name: "The Boeing Company", exchange: "NYSE", ticker: "BA" },
  { name: "Johnson & Johnson", exchange: "NYSE", ticker: "JNJ" },
  { name: "The Procter & Gamble Company", exchange: "NYSE", ticker: "PG" },
  { name: "Visa Inc.", exchange: "NYSE", ticker: "V" },
  { name: "JPMorgan Chase & Co.", exchange: "NYSE", ticker: "JPM" },
  { name: "The Coca-Cola Company", exchange: "NYSE", ticker: "KO" },
  { name: "Pfizer Inc.", exchange: "NYSE", ticker: "PFE" },
  { name: "Bank of America Corp", exchange: "NYSE", ticker: "BAC" },
  { name: "Walmart Inc.", exchange: "NYSE", ticker: "WMT" },
  { name: "Chevron Corporation", exchange: "NYSE", ticker: "CVX" },
  { name: "AT&T Inc.", exchange: "NYSE", ticker: "T" },
  { name: "Verizon Communications", exchange: "NYSE", ticker: "VZ" },
  { name: "Exxon Mobil Corporation", exchange: "NYSE", ticker: "XOM" },
  { name: "Merck & Co., Inc.", exchange: "NYSE", ticker: "MRK" },
  { name: "Intel Corporation", exchange: "NASDAQ", ticker: "INTC" },
  { name: "Cisco Systems, Inc.", exchange: "NASDAQ", ticker: "CSCO" },
  { name: "American Express Company", exchange: "NYSE", ticker: "AXP" },
  { name: "3M Company", exchange: "NYSE", ticker: "MMM" },
  { name: "The Home Depot, Inc.", exchange: "NYSE", ticker: "HD" },
  { name: "McDonald's Corporation", exchange: "NYSE", ticker: "MCD" },
  { name: "The Walt Disney Company", exchange: "NYSE", ticker: "DIS" },
  {
    name: "International Business Machines Corporation",
    exchange: "NYSE",
    ticker: "IBM",
  },
  { name: "Caterpillar Inc.", exchange: "NYSE", ticker: "CAT" },
  { name: "DuPont de Nemours, Inc.", exchange: "NYSE", ticker: "DD" },
  { name: "UnitedHealth Group Incorporated", exchange: "NYSE", ticker: "UNH" },
  { name: "The Goldman Sachs Group, Inc.", exchange: "NYSE", ticker: "GS" },
  { name: "The Boeing Company", exchange: "NYSE", ticker: "BA" },
  { name: "Coca-Cola Company", exchange: "NYSE", ticker: "KO" },
  { name: "American Airlines Group Inc.", exchange: "NASDAQ", ticker: "AAL" },
  { name: "Delta Air Lines, Inc.", exchange: "NYSE", ticker: "DAL" },
  { name: "Southwest Airlines Co.", exchange: "NYSE", ticker: "LUV" },
  { name: "United Airlines Holdings, Inc.", exchange: "NASDAQ", ticker: "UAL" },
  { name: "Lockheed Martin Corporation", exchange: "NYSE", ticker: "LMT" },
  { name: "Northrop Grumman Corporation", exchange: "NYSE", ticker: "NOC" },
  {
    name: "Raytheon Technologies Corporation",
    exchange: "NYSE",
    ticker: "RTX",
  },
  { name: "General Dynamics Corporation", exchange: "NYSE", ticker: "GD" },
  { name: "American Airlines Group", exchange: "NASDAQ", ticker: "AAL" },
  { name: "AT&T Inc.", exchange: "NYSE", ticker: "T" },
  { name: "Bank of America Corp", exchange: "NYSE", ticker: "BAC" },
  { name: "Coca-Cola Company", exchange: "NYSE", ticker: "KO" },
  { name: "Delta Air Lines, Inc.", exchange: "NYSE", ticker: "DAL" },
  { name: "Exxon Mobil Corporation", exchange: "NYSE", ticker: "XOM" },

  { name: "General Motors Company", exchange: "NYSE", ticker: "GM" },
  { name: "Hewlett Packard Enterprise", exchange: "NYSE", ticker: "HPE" },
  { name: "JPMorgan Chase & Co.", exchange: "NYSE", ticker: "JPM" },
  { name: "Kraft Heinz Co", exchange: "NASDAQ", ticker: "KHC" },
  { name: "Lockheed Martin Corporation", exchange: "NYSE", ticker: "LMT" },
  { name: "McDonald's Corp", exchange: "NYSE", ticker: "MCD" },
  { name: "Netflix, Inc.", exchange: "NASDAQ", ticker: "NFLX" },
  { name: "Oracle Corporation", exchange: "NYSE", ticker: "ORCL" },
  { name: "PepsiCo, Inc.", exchange: "NASDAQ", ticker: "PEP" },
  { name: "Qualcomm Inc", exchange: "NASDAQ", ticker: "QCOM" },
  {
    name: "Raytheon Technologies Corporation",
    exchange: "NYSE",
    ticker: "RTX",
  },
  { name: "Southwest Airlines Co", exchange: "NYSE", ticker: "LUV" },
  { name: "Twitter, Inc.", exchange: "NYSE", ticker: "TWTR" },
  { name: "UnitedHealth Group Incorporated", exchange: "NYSE", ticker: "UNH" },
  { name: "Visa Inc", exchange: "NYSE", ticker: "V" },
  { name: "Walmart Inc", exchange: "NYSE", ticker: "WMT" },
  { name: "Exxon Mobil Corporation", exchange: "NYSE", ticker: "XOM" },
  { name: "Zoom Video Communications, Inc.", exchange: "NASDAQ", ticker: "ZM" },
];
